### PR TITLE
Update deps

### PR DESCRIPTION
**Pull request by sepetrov**
# Added
- `minikube_kafka` test matrix for Amazon EKS supported Kubernetes versions: v1.14.9, v1.15.11, v1.16.13, v1.17.9, v1.18.9
- `script/build-manifests.sh` to prepare build manifests
- default HTTP backend to `minikube`

# Changed
- `github.com/kubeless/kubeless` from v1.0.0 to v1.0.7
- `github.com/golang/protobuf` from v1.4.2 to v1.2.0 to resolve issue with indirect dependencies causing `go mod tidy` to fail
- `k8s.io/client-go` from v5.0.0 to v7.0.0
- `minikube` from v1.2.0 to v1.11.0

# Removed
- integration test checking logs for errors, which does not detect if the error was resolved

**TODOs**:
 - [x] Ready to review
 - [x] Automated Tests
 - [ ] Docs

### CODE REVIEW

**Comment by faxioman** [comment]
@sepetrov There are some tests that are intermittently failing ... timeout problem? All tests are always working when performed locally...

cc @andresmgot

**Comment by faxioman** [comment]
@sepetrov increasing the timeout has brought benefits ;)
Anyway, one test has timed out.

Ideas @andresmgot ?

**Comment by sepetrov** [comment]
@faxioman , increasing the timeout should help. From my experience, intermittent failures during function deployments are possible. I'd like to get a green build before having the PR merged.

**Review by andresmgot — APPROVED** [review]
Thank you both @sepetrov and @faxioman for getting back to this! Changes look good to me but it's true that it seems that it's consistently failing for Kubernetes 1.16 (which is weird). I have relaunched the test, let me check if I can find what can be failing.

**Comment by andresmgot** [comment]
I retried the build with SSH and it worked. It seems indeed an issue with the Ingress controller, taking to much to assign IPs. Let's see if it was a transitory error.

**Pull request merged**
